#!/bin/bash
/usr/bin/defaults write /Library/Preferences/com.oracle.java.Java-Updater JavaAutoUpdateEnabled -bool false
/usr/bin/defaults write /Library/Preferences/com.oracle.javadeployment deployment.expiration.check.enabled -bool false